version: "3.8"

networks:
  springboot-mysql-net:

services:

  mariadb:
    container_name: mysqldb
    image: "mariadb:latest"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=kadem
    networks:
      - springboot-mysql-net

  kadem:
    container_name: kadem_container
    build: ./
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/kadem?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8089:8089"
    image: kadem
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net
    restart: unless-stopped

