version: "3.8"

networks:
  springboot-mysql-net:


services:

  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=kaddem
     networks:
      - springboot-mysql-net

  kadem:
    build: ./
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/kaddem?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=
    ports:
      - 8089:8089
    image: emnataalouch-5twin4-g1
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net


