version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: "mariadb:latest"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=kaddem
    networks:
      - springboot-mysql-net



  kadem:
    build: ./
    image: acilfarhat-5twin4-g3
    restart: unless-stopped
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/kaddem?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net

