version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=kaddem
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./devopsProject
    restart: on-failure
    env_file: ./.env
    ports:
      - 8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/kaddem?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
