version: "3.8"

#--------------------------------------------------------Networks--------------------------------------------------------#

networks:
  springboot-mysql-net:

services:

#--------------------------------------------------------Database--------------------------------------------------------#

  mariadb:
    container_name: mariadb
    image: "mariadb:latest"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=kaddem
    networks:
      - springboot-mysql-net
  


#--------------------------------------------------------Application--------------------------------------------------------#

  kadem:
    container_name: kadem_container
    build: ./
    # restart: unless-stopped
    environment:
      - spring.datasource.url=jdbc:mysql://mariadb:3306/kaddem?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8089:8089
    image: rayenoueslati-5twin4-g1-kadem
    depends_on:
      - mariadb
    networks:
      - springboot-mysql-net