version: "3.8"

volumes:
  db:
  
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=kaddem
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql


  kadem:
    container_name: kadem_container
    depends_on:
      - mysqldb
    build: ./
    image: emnataalouch/emnataalouch-5twin4-g1
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysqldb:3306/kaddem?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC",        
        "spring.datasource.username" : "root",
        "spring.datasource.password" :  "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

 


    
  
