version: "3.8"

networks:
  mynetwork:

services:

  mydb:
    container_name: mariadb
    image: "mariadb:latest"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=kaddem
    networks:
      - mynetwork

  kadem_nour:
    container_name: kadem_nour_container
    build: ./
    restart: unless-stopped
    environment:
      - spring.datasource.url=jdbc:mysql://mydb:3306/kaddem?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8089:8089"
    depends_on:
      - mydb
    networks:
      - mynetwork