version: "3.8"

networks:
  mynetwork:

services:

  mariadb:
    container_name: mariadb
    image: "mariadb:latest"
    restart: unless-stoppeds
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=kaddem
    networks:
      - mynetwork

  kadem_nour:
    container_name: kadem_nour_container
    build: ./
    restart: unless-stopped
    environment:
      - spring.datasource.url=jdbc:mysql://mariadb:3306/kaddemDBB?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8089:8089"
    depends_on: 
     - mariadb
    networks:
      - mynetwork