version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: "mariadb:latest"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=GhaithDBB
    networks:
      - my_network



  departement_app:
    build: ./
    image: ghaithbenrzig-5twin4-g3
    restart: unless-stopped
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/GhaithDBB?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      - my_network

  front_app:
    build: ./Kadem-web-app
    image: front
    restart: unless-stopped
    ports:
      - 4200:80
    networks:
      - my_network


volumes:
  db_vol:

networks:
  my_network:


