version: "3.8"

networks:
  mynetwork:

services:

  mariadb:
    container_name: mariadb
    image: "mariadb:latest"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=kaddem_nour
    networks:
      - mynetwork

  kadem:
    container_name: kadem_container
    build: ./
    image: kadem
    restart: unless-stopped
    environment:
      - spring.datasource.url=jdbc:mysql://mariadb:3306/kaddem?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8089:8089"
    depends_on:
      - mariadb
    networks:
      - mynetwork